/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * ZETTA
 * DOCS API ZETTA
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'

import type {
  BodyUploadFileApiFilesPost,
  FileResponse,
  HTTPValidationError,
  LoginRequest,
  LoginResponse,
  LogoutResponse,
  MeResponse,
  RegisterResponse,
  UserCreate,
} from './model'

import { customInstance } from './axios.config'
import type { BodyType } from './axios.config'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Health
 */
export type healthGetResponse200 = {
  data: unknown
  status: 200
}

export type healthGetResponseSuccess = healthGetResponse200 & {
  headers: Headers
}
export type healthGetResponse = healthGetResponseSuccess

export const getHealthGetUrl = () => {
  return `/`
}

export const healthGet = async (options?: RequestInit): Promise<healthGetResponse> => {
  return customInstance<healthGetResponse>(getHealthGetUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getHealthGetQueryKey = () => {
  return [] as const
}

export const getHealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGet>>, TError, TData>>
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getHealthGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthGet>>> = ({ signal }) =>
    healthGet({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthGet>>,
    TError,
    TData
  >
}

export type HealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthGet>>>
export type HealthGetQueryError = unknown

/**
 * @summary Health
 */

export function useHealthGet<TData = Awaited<ReturnType<typeof healthGet>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGet>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Register
 */
export type registerAuthRegisterPostResponse200 = {
  data: RegisterResponse
  status: 200
}

export type registerAuthRegisterPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type registerAuthRegisterPostResponseSuccess = registerAuthRegisterPostResponse200 & {
  headers: Headers
}
export type registerAuthRegisterPostResponseError = registerAuthRegisterPostResponse422 & {
  headers: Headers
}

export type registerAuthRegisterPostResponse =
  | registerAuthRegisterPostResponseSuccess
  | registerAuthRegisterPostResponseError

export const getRegisterAuthRegisterPostUrl = () => {
  return `/auth/register`
}

export const registerAuthRegisterPost = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<registerAuthRegisterPostResponse> => {
  return customInstance<registerAuthRegisterPostResponse>(getRegisterAuthRegisterPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreate),
  })
}

export const getRegisterAuthRegisterPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerAuthRegisterPost>>,
    TError,
    { data: BodyType<UserCreate> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerAuthRegisterPost>>,
  TError,
  { data: BodyType<UserCreate> },
  TContext
> => {
  const mutationKey = ['registerAuthRegisterPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerAuthRegisterPost>>,
    { data: BodyType<UserCreate> }
  > = (props) => {
    const { data } = props ?? {}

    return registerAuthRegisterPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RegisterAuthRegisterPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerAuthRegisterPost>>
>
export type RegisterAuthRegisterPostMutationBody = BodyType<UserCreate>
export type RegisterAuthRegisterPostMutationError = HTTPValidationError

/**
 * @summary Register
 */
export const useRegisterAuthRegisterPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerAuthRegisterPost>>,
      TError,
      { data: BodyType<UserCreate> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof registerAuthRegisterPost>>,
  TError,
  { data: BodyType<UserCreate> },
  TContext
> => {
  return useMutation(getRegisterAuthRegisterPostMutationOptions(options), queryClient)
}

/**
 * @summary Login
 */
export type loginAuthLoginPostResponse200 = {
  data: LoginResponse
  status: 200
}

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginAuthLoginPostResponseSuccess = loginAuthLoginPostResponse200 & {
  headers: Headers
}
export type loginAuthLoginPostResponseError = loginAuthLoginPostResponse422 & {
  headers: Headers
}

export type loginAuthLoginPostResponse =
  | loginAuthLoginPostResponseSuccess
  | loginAuthLoginPostResponseError

export const getLoginAuthLoginPostUrl = () => {
  return `/auth/login`
}

export const loginAuthLoginPost = async (
  loginRequest: LoginRequest,
  options?: RequestInit,
): Promise<loginAuthLoginPostResponse> => {
  return customInstance<loginAuthLoginPostResponse>(getLoginAuthLoginPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest),
  })
}

export const getLoginAuthLoginPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginAuthLoginPost>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginAuthLoginPost>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  const mutationKey = ['loginAuthLoginPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginAuthLoginPost>>,
    { data: BodyType<LoginRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return loginAuthLoginPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginAuthLoginPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginAuthLoginPost>>
>
export type LoginAuthLoginPostMutationBody = BodyType<LoginRequest>
export type LoginAuthLoginPostMutationError = HTTPValidationError

/**
 * @summary Login
 */
export const useLoginAuthLoginPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginAuthLoginPost>>,
      TError,
      { data: BodyType<LoginRequest> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof loginAuthLoginPost>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  return useMutation(getLoginAuthLoginPostMutationOptions(options), queryClient)
}

/**
 * @summary Me
 */
export type meAuthMeGetResponse200 = {
  data: MeResponse
  status: 200
}

export type meAuthMeGetResponseSuccess = meAuthMeGetResponse200 & {
  headers: Headers
}
export type meAuthMeGetResponse = meAuthMeGetResponseSuccess

export const getMeAuthMeGetUrl = () => {
  return `/auth/me`
}

export const meAuthMeGet = async (options?: RequestInit): Promise<meAuthMeGetResponse> => {
  return customInstance<meAuthMeGetResponse>(getMeAuthMeGetUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getMeAuthMeGetQueryKey = () => {
  return ['auth', 'me'] as const
}

export const getMeAuthMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof meAuthMeGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>>
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getMeAuthMeGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof meAuthMeGet>>> = ({ signal }) =>
    meAuthMeGet({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof meAuthMeGet>>,
    TError,
    TData
  >
}

export type MeAuthMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof meAuthMeGet>>>
export type MeAuthMeGetQueryError = unknown

/**
 * @summary Me
 */

export function useMeAuthMeGet<TData = Awaited<ReturnType<typeof meAuthMeGet>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMeAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Logout
 */
export type logoutAuthLogoutPostResponse200 = {
  data: LogoutResponse
  status: 200
}

export type logoutAuthLogoutPostResponseSuccess = logoutAuthLogoutPostResponse200 & {
  headers: Headers
}
export type logoutAuthLogoutPostResponse = logoutAuthLogoutPostResponseSuccess

export const getLogoutAuthLogoutPostUrl = () => {
  return `/auth/logout`
}

export const logoutAuthLogoutPost = async (
  options?: RequestInit,
): Promise<logoutAuthLogoutPostResponse> => {
  return customInstance<logoutAuthLogoutPostResponse>(getLogoutAuthLogoutPostUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getLogoutAuthLogoutPostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['logoutAuthLogoutPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
    void
  > = () => {
    return logoutAuthLogoutPost(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LogoutAuthLogoutPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutAuthLogoutPost>>
>

export type LogoutAuthLogoutPostMutationError = unknown

/**
 * @summary Logout
 */
export const useLogoutAuthLogoutPost = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutAuthLogoutPostMutationOptions(options), queryClient)
}

/**
 * @summary Upload File
 */
export type uploadFileApiFilesPostResponse200 = {
  data: FileResponse
  status: 200
}

export type uploadFileApiFilesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadFileApiFilesPostResponseSuccess = uploadFileApiFilesPostResponse200 & {
  headers: Headers
}
export type uploadFileApiFilesPostResponseError = uploadFileApiFilesPostResponse422 & {
  headers: Headers
}

export type uploadFileApiFilesPostResponse =
  | uploadFileApiFilesPostResponseSuccess
  | uploadFileApiFilesPostResponseError

export const getUploadFileApiFilesPostUrl = () => {
  return `/api/files/`
}

export const uploadFileApiFilesPost = async (
  bodyUploadFileApiFilesPost: BodyUploadFileApiFilesPost,
  options?: RequestInit,
): Promise<uploadFileApiFilesPostResponse> => {
  const formData = new FormData()
  formData.append(`file_upload`, bodyUploadFileApiFilesPost.file_upload)

  return customInstance<uploadFileApiFilesPostResponse>(getUploadFileApiFilesPostUrl(), {
    ...options,
    method: 'POST',
    body: formData,
  })
}

export const getUploadFileApiFilesPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
    TError,
    { data: BodyType<BodyUploadFileApiFilesPost> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
  TError,
  { data: BodyType<BodyUploadFileApiFilesPost> },
  TContext
> => {
  const mutationKey = ['uploadFileApiFilesPost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
    { data: BodyType<BodyUploadFileApiFilesPost> }
  > = (props) => {
    const { data } = props ?? {}

    return uploadFileApiFilesPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UploadFileApiFilesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadFileApiFilesPost>>
>
export type UploadFileApiFilesPostMutationBody = BodyType<BodyUploadFileApiFilesPost>
export type UploadFileApiFilesPostMutationError = HTTPValidationError

/**
 * @summary Upload File
 */
export const useUploadFileApiFilesPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
      TError,
      { data: BodyType<BodyUploadFileApiFilesPost> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
  TError,
  { data: BodyType<BodyUploadFileApiFilesPost> },
  TContext
> => {
  return useMutation(getUploadFileApiFilesPostMutationOptions(options), queryClient)
}
