/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * ZETTA
 * DOCS API ZETTA
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  BodyUploadFileApiFilesPost,
  FileResponse,
  HTTPValidationError,
  LoginRequest,
  LoginResponse,
  LogoutResponse,
  MeResponse,
  RegisterResponse,
  UserCreate,
} from './model'

import { customInstance } from './axios.config'

/**
 * @summary Health
 */
export const healthGet = (signal?: AbortSignal) => {
  return customInstance<unknown>({ url: `/`, method: 'GET', signal })
}

export const getHealthGetQueryKey = () => {
  return [] as const
}

export const getHealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGet>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getHealthGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthGet>>> = ({ signal }) =>
    healthGet(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthGet>>,
    TError,
    TData
  >
}

export type HealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthGet>>>
export type HealthGetQueryError = unknown

/**
 * @summary Health
 */

export function useHealthGet<TData = Awaited<ReturnType<typeof healthGet>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGet>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Register
 */
export const registerAuthRegisterPost = (
  userCreate: MaybeRef<UserCreate>,
  signal?: AbortSignal,
) => {
  userCreate = unref(userCreate)

  return customInstance<RegisterResponse>({
    url: `/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userCreate,
    signal,
  })
}

export const getRegisterAuthRegisterPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerAuthRegisterPost>>,
    TError,
    { data: UserCreate },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerAuthRegisterPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  const mutationKey = ['registerAuthRegisterPost']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerAuthRegisterPost>>,
    { data: UserCreate }
  > = (props) => {
    const { data } = props ?? {}

    return registerAuthRegisterPost(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type RegisterAuthRegisterPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerAuthRegisterPost>>
>
export type RegisterAuthRegisterPostMutationBody = UserCreate
export type RegisterAuthRegisterPostMutationError = HTTPValidationError

/**
 * @summary Register
 */
export const useRegisterAuthRegisterPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerAuthRegisterPost>>,
      TError,
      { data: UserCreate },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof registerAuthRegisterPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  return useMutation(getRegisterAuthRegisterPostMutationOptions(options), queryClient)
}

/**
 * @summary Login
 */
export const loginAuthLoginPost = (loginRequest: MaybeRef<LoginRequest>, signal?: AbortSignal) => {
  loginRequest = unref(loginRequest)

  return customInstance<LoginResponse>({
    url: `/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginRequest,
    signal,
  })
}

export const getLoginAuthLoginPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginAuthLoginPost>>,
    TError,
    { data: LoginRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginAuthLoginPost>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationKey = ['loginAuthLoginPost']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginAuthLoginPost>>,
    { data: LoginRequest }
  > = (props) => {
    const { data } = props ?? {}

    return loginAuthLoginPost(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginAuthLoginPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginAuthLoginPost>>
>
export type LoginAuthLoginPostMutationBody = LoginRequest
export type LoginAuthLoginPostMutationError = HTTPValidationError

/**
 * @summary Login
 */
export const useLoginAuthLoginPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginAuthLoginPost>>,
      TError,
      { data: LoginRequest },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof loginAuthLoginPost>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  return useMutation(getLoginAuthLoginPostMutationOptions(options), queryClient)
}

/**
 * @summary Me
 */
export const meAuthMeGet = (signal?: AbortSignal) => {
  return customInstance<MeResponse>({ url: `/auth/me`, method: 'GET', signal })
}

export const getMeAuthMeGetQueryKey = () => {
  return ['auth', 'me'] as const
}

export const getMeAuthMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof meAuthMeGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getMeAuthMeGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof meAuthMeGet>>> = ({ signal }) =>
    meAuthMeGet(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof meAuthMeGet>>,
    TError,
    TData
  >
}

export type MeAuthMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof meAuthMeGet>>>
export type MeAuthMeGetQueryError = unknown

/**
 * @summary Me
 */

export function useMeAuthMeGet<TData = Awaited<ReturnType<typeof meAuthMeGet>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMeAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Logout
 */
export const logoutAuthLogoutPost = (signal?: AbortSignal) => {
  return customInstance<LogoutResponse>({ url: `/auth/logout`, method: 'POST', signal })
}

export const getLogoutAuthLogoutPostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
    TError,
    void,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['logoutAuthLogoutPost']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
    void
  > = () => {
    return logoutAuthLogoutPost()
  }

  return { mutationFn, ...mutationOptions }
}

export type LogoutAuthLogoutPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutAuthLogoutPost>>
>

export type LogoutAuthLogoutPostMutationError = unknown

/**
 * @summary Logout
 */
export const useLogoutAuthLogoutPost = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
      TError,
      void,
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutAuthLogoutPostMutationOptions(options), queryClient)
}

/**
 * @summary Upload File
 */
export const uploadFileApiFilesPost = (
  bodyUploadFileApiFilesPost: MaybeRef<BodyUploadFileApiFilesPost>,
  signal?: AbortSignal,
) => {
  bodyUploadFileApiFilesPost = unref(bodyUploadFileApiFilesPost)
  const formData = new FormData()
  formData.append(`file_upload`, bodyUploadFileApiFilesPost.file_upload)

  return customInstance<FileResponse>({
    url: `/api/files/`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
    signal,
  })
}

export const getUploadFileApiFilesPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
    TError,
    { data: BodyUploadFileApiFilesPost },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
  TError,
  { data: BodyUploadFileApiFilesPost },
  TContext
> => {
  const mutationKey = ['uploadFileApiFilesPost']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
    { data: BodyUploadFileApiFilesPost }
  > = (props) => {
    const { data } = props ?? {}

    return uploadFileApiFilesPost(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UploadFileApiFilesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadFileApiFilesPost>>
>
export type UploadFileApiFilesPostMutationBody = BodyUploadFileApiFilesPost
export type UploadFileApiFilesPostMutationError = HTTPValidationError

/**
 * @summary Upload File
 */
export const useUploadFileApiFilesPost = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
      TError,
      { data: BodyUploadFileApiFilesPost },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof uploadFileApiFilesPost>>,
  TError,
  { data: BodyUploadFileApiFilesPost },
  TContext
> => {
  return useMutation(getUploadFileApiFilesPostMutationOptions(options), queryClient)
}
