/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * ZETTA
 * DOCS API ZETTA
 * OpenAPI spec version: 0.1.0
 */

export interface FileBase {
  id: string
  nombre_original: string
  path: string
  fecha_creacion: string
  id_usuario: string
}
