/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * ZETTA
 * DOCS API ZETTA
 * OpenAPI spec version: 0.1.0
 */
import type { UserReturn } from './userReturn'

export interface MeResponse {
  usuario: UserReturn
}
