/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * ZETTA
 * DOCS API ZETTA
 * OpenAPI spec version: 0.1.0
 */

export interface UserCreate {
  /**
   * @minLength 4
   * @maxLength 20
   */
  nombre: string
  /** @maxLength 120 */
  correo: string
  /** @minLength 6 */
  contraseña: string
  /** @minLength 6 */
  contraseña_repetir: string
}
