/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * ZETTA
 * DOCS API ZETTA
 * OpenAPI spec version: 0.1.0
 */

export interface ValidationError {
  loc: (string | number)[]
  msg: string
  type: string
}
