"""añadir id carpeta padre a carpeta

Revision ID: 2c98dc7ba8a5
Revises: 9ba140205b2c
Create Date: 2026-03-21 17:57:54.760020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c98dc7ba8a5'
down_revision: Union[str, Sequence[str], None] = '9ba140205b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpetas', sa.Column('id_carpeta', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'carpetas', 'carpetas', ['id_carpeta'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carpetas', type_='foreignkey')
    op.drop_column('carpetas', 'id_carpeta')
    # ### end Alembic commands ###
