"""añadir fecha eliminacion file y folder

Revision ID: 2f817ab0c3d5
Revises: 2c98dc7ba8a5
Create Date: 2026-03-29 15:35:47.332187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f817ab0c3d5'
down_revision: Union[str, Sequence[str], None] = '2c98dc7ba8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivos', sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True))
    op.add_column('carpetas', sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpetas', 'fecha_eliminacion')
    op.drop_column('archivos', 'fecha_eliminacion')
    # ### end Alembic commands ###
