"""añadir tabla carpetas

Revision ID: 5568ab072f58
Revises: 8d6ac58ba73c
Create Date: 2026-02-26 16:33:17.736109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5568ab072f58'
down_revision: Union[str, Sequence[str], None] = '8d6ac58ba73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpetas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_original', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carpetas')
    # ### end Alembic commands ###
