"""añadir tabla archivos compartidos

Revision ID: 62684b1a03f9
Revises: ca6968767222
Create Date: 2026-04-22 17:38:25.712507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62684b1a03f9'
down_revision: Union[str, Sequence[str], None] = 'ca6968767222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos_compartidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha_compartido', sa.DateTime(), nullable=True),
    sa.Column('id_propietario', sa.UUID(), nullable=False),
    sa.Column('id_receptor', sa.UUID(), nullable=False),
    sa.Column('id_archivo', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_archivo'], ['archivos.id'], ),
    sa.ForeignKeyConstraint(['id_propietario'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_receptor'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivos_compartidos')
    # ### end Alembic commands ###
