"""añadir columna tamaño archivo

Revision ID: 8d6ac58ba73c
Revises: e689dc2a794a
Create Date: 2026-02-14 23:39:36.795910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6ac58ba73c'
down_revision: Union[str, Sequence[str], None] = 'e689dc2a794a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivos', sa.Column('tamaño_bytes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archivos', 'tamaño_bytes')
    # ### end Alembic commands ###
