"""añadir id carpeta a archivo

Revision ID: 9ba140205b2c
Revises: a034d202a0ed
Create Date: 2026-03-09 18:53:24.783686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba140205b2c'
down_revision: Union[str, Sequence[str], None] = 'a034d202a0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivos', sa.Column('id_carpeta', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'archivos', 'carpetas', ['id_carpeta'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'archivos', type_='foreignkey')
    op.drop_column('archivos', 'id_carpeta')
    # ### end Alembic commands ###
