"""añadir bool favorito a archivos y carpetas

Revision ID: bf210665e3bb
Revises: e4e9c9706355
Create Date: 2026-05-20 17:24:45.970147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf210665e3bb'
down_revision: Union[str, Sequence[str], None] = 'e4e9c9706355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivos', sa.Column(
        'favorito', sa.Boolean(), nullable=False, server_default="false"))
    op.add_column('carpetas', sa.Column(
        'favorito', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpetas', 'favorito')
    op.drop_column('archivos', 'favorito')
    # ### end Alembic commands ###
