"""añadir delete cascade a hijos carpeta

Revision ID: c08a4c8d977f
Revises: 2f817ab0c3d5
Create Date: 2026-04-12 15:52:46.027918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08a4c8d977f'
down_revision: Union[str, Sequence[str], None] = '2f817ab0c3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('carpetas_id_carpeta_fkey'), 'carpetas', type_='foreignkey')
    op.create_foreign_key(None, 'carpetas', 'carpetas', ['id_carpeta'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carpetas', type_='foreignkey')
    op.create_foreign_key(op.f('carpetas_id_carpeta_fkey'), 'carpetas', 'carpetas', ['id_carpeta'], ['id'])
    # ### end Alembic commands ###
