"""añadir carpetas compartidas

Revision ID: ca6968767222
Revises: c08a4c8d977f
Create Date: 2026-04-22 17:23:21.250924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6968767222'
down_revision: Union[str, Sequence[str], None] = 'c08a4c8d977f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpetas_compartidas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha_compartido', sa.DateTime(), nullable=True),
    sa.Column('id_propietario', sa.UUID(), nullable=False),
    sa.Column('id_receptor', sa.UUID(), nullable=False),
    sa.Column('id_carpeta', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_carpeta'], ['carpetas.id'], ),
    sa.ForeignKeyConstraint(['id_propietario'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_receptor'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carpetas_compartidas')
    # ### end Alembic commands ###
