"""migrar favoritos a nuevas tablas separadas

Revision ID: e17185bef84e
Revises: ec1cb9523075
Create Date: 2026-05-22 20:09:30.935422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e17185bef84e'
down_revision: Union[str, Sequence[str], None] = 'ec1cb9523075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpetas_favoritas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha_favorito', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_carpeta', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_carpeta'], ['carpetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivos_favoritos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha_favorito', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_archivo', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_archivo'], ['archivos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('archivos', 'favorito')
    op.drop_column('archivos', 'fecha_favorito')
    op.drop_column('carpetas', 'favorito')
    op.drop_column('carpetas', 'fecha_favorito')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpetas', sa.Column('fecha_favorito', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('carpetas', sa.Column('favorito', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('archivos', sa.Column('fecha_favorito', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('archivos', sa.Column('favorito', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_table('archivos_favoritos')
    op.drop_table('carpetas_favoritas')
    # ### end Alembic commands ###
