"""añadir delete cascade compartidos

Revision ID: e4e9c9706355
Revises: 62684b1a03f9
Create Date: 2026-04-27 17:49:56.579595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e9c9706355'
down_revision: Union[str, Sequence[str], None] = '62684b1a03f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('archivos_compartidos_id_archivo_fkey'), 'archivos_compartidos', type_='foreignkey')
    op.create_foreign_key(None, 'archivos_compartidos', 'archivos', ['id_archivo'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('carpetas_compartidas_id_carpeta_fkey'), 'carpetas_compartidas', type_='foreignkey')
    op.create_foreign_key(None, 'carpetas_compartidas', 'carpetas', ['id_carpeta'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carpetas_compartidas', type_='foreignkey')
    op.create_foreign_key(op.f('carpetas_compartidas_id_carpeta_fkey'), 'carpetas_compartidas', 'carpetas', ['id_carpeta'], ['id'])
    op.drop_constraint(None, 'archivos_compartidos', type_='foreignkey')
    op.create_foreign_key(op.f('archivos_compartidos_id_archivo_fkey'), 'archivos_compartidos', 'archivos', ['id_archivo'], ['id'])
    # ### end Alembic commands ###
