"""añadir tabla archivos

Revision ID: e689dc2a794a
Revises: f21879dde138
Create Date: 2026-01-24 00:20:32.436375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e689dc2a794a'
down_revision: Union[str, Sequence[str], None] = 'f21879dde138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_original', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivos')
    # ### end Alembic commands ###
