"""añadir fecha favorito

Revision ID: ec1cb9523075
Revises: bf210665e3bb
Create Date: 2026-05-20 19:33:06.637588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1cb9523075'
down_revision: Union[str, Sequence[str], None] = 'bf210665e3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivos', sa.Column('fecha_favorito', sa.DateTime(), nullable=True))
    op.add_column('carpetas', sa.Column('fecha_favorito', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpetas', 'fecha_favorito')
    op.drop_column('archivos', 'fecha_favorito')
    # ### end Alembic commands ###
