/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Files */
        get: operations["get_files_api_files_get"];
        put?: never;
        /** Upload File */
        post: operations["upload_file_api_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id_archivo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Files */
        get: operations["download_files_api_files__id_archivo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Files */
        get: operations["get_files_api_folders_get"];
        put?: never;
        /** Create Folder */
        post: operations["create_folder_api_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders/{id_carpeta}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Files Of Folder */
        get: operations["get_files_of_folder_api_folders__id_carpeta__files_get"];
        put?: never;
        /** Upload File To Folder */
        post: operations["upload_file_to_folder_api_folders__id_carpeta__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_file_api_files_post */
        Body_upload_file_api_files_post: {
            /** File Upload */
            file_upload: string[];
        };
        /** Body_upload_file_to_folder_api_folders__id_carpeta__files_post */
        Body_upload_file_to_folder_api_folders__id_carpeta__files_post: {
            /** File Upload */
            file_upload: string[];
        };
        /** FileBase */
        FileBase: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre Original */
            nombre_original: string;
            /** Path */
            path: string;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
            /** Tamaño Bytes */
            "tama\u00F1o_bytes": number;
            /**
             * Id Usuario
             * Format: uuid
             */
            id_usuario: string;
            /** Id Carpeta */
            id_carpeta: string | null;
            /** Nombre Usuario */
            nombre_usuario: string;
        };
        /** FileResponse */
        FileResponse: {
            /** Msg */
            msg: string;
            /** Archivos */
            archivos: components["schemas"]["FileBase"][];
        };
        /** FolderBase */
        FolderBase: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre Original */
            nombre_original: string;
            /** Path */
            path: string;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
            /**
             * Id Usuario
             * Format: uuid
             */
            id_usuario: string;
            /** Nombre Usuario */
            nombre_usuario: string;
        };
        /** FolderRequest */
        FolderRequest: {
            /** Nombre Carpeta */
            nombre_carpeta: string;
        };
        /** FolderResponse */
        FolderResponse: {
            /** Msg */
            msg: string;
            carpeta: components["schemas"]["FolderBase"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Nombre */
            nombre: string;
            /** Contraseña */
            "contrase\u00F1a": string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Msg */
            msg: string;
            usuario: components["schemas"]["UserReturn"];
        };
        /** LogoutResponse */
        LogoutResponse: {
            /** Msg */
            msg: string;
        };
        /** MeResponse */
        MeResponse: {
            usuario: components["schemas"]["UserReturn"];
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** Msg */
            msg: string;
            usuario: components["schemas"]["UserReturn"];
        };
        /** UploadFileFolderResponse */
        UploadFileFolderResponse: {
            /** Msg */
            msg: string;
            /** Archivos */
            archivos: components["schemas"]["FileBase"][];
        };
        /** UserCreate */
        UserCreate: {
            /** Nombre */
            nombre: string;
            /**
             * Correo
             * Format: email
             */
            correo: string;
            /** Contraseña */
            "contrase\u00F1a": string;
            /** Contraseña Repetir */
            "contrase\u00F1a_repetir": string;
        };
        /** UserReturn */
        UserReturn: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Correo */
            correo: string;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    get_files_api_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileBase"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_files_api_files__id_archivo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_archivo: string;
            };
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_files_api_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderBase"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_folder_api_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_files_of_folder_api_folders__id_carpeta__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_carpeta: string;
            };
            cookie?: {
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileBase"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_to_folder_api_folders__id_carpeta__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_carpeta: string;
            };
            cookie?: {
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_to_folder_api_folders__id_carpeta__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadFileFolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
